### ISSUE TITLE
一直在获取IP地址

### ISSUE THREAD

**Issue by WhatHowie** [Just-Hack-For-Fun/IP-Recorder#1]
一直在获取IP地址
![image](https://github.com/user-attachments/assets/bc13f6fb-19e4-45d6-8a87-13580df23c1e)

**Comment by Just-Hack-For-Fun** [comment]
程序默认会重试 5 次，每次 500 毫秒，如果过一段时间还是这样，说明你的网络与获取本机IP的网站之间连接可能有问题

**Comment by Arrowzzzzzz** [comment]
我这边也是这样，一直回去 IP 地址，但是点击导出结果后能看到 IP 地址

> 程序默认会重试 5 次，每次 500 毫秒，如果过一段时间还是这样，说明你的网络与获取本机IP的网站之间连接可能有问题

**Comment by Just-Hack-For-Fun** [comment]
过了一会儿后是否可以正常获取IP地址呢

**Comment by yinsel** [comment]
> 过了一会儿后是否可以正常获取IP地址呢

目前无法获取IP地址，代理是可用的，但检测代理也不可用

**Comment by Just-Hack-For-Fun** [comment]
方便提供以下代理情况吗？ 什么软件起的，用什么协议，是否公网可访问，是否需要密码等

**Comment by yinsel** [comment]
> 方便提供以下代理情况吗？ 什么软件起的，用什么协议，是否公网可访问，是否需要密码等

目前就是无法使用，无代理也无法获取IP地址，网络正常

![image](https://github.com/user-attachments/assets/17216316-4ca8-4962-8d0c-fddd040af09a)

**Comment by yinsel** [comment]
> 方便提供以下代理情况吗？ 什么软件起的，用什么协议，是否公网可访问，是否需要密码等

目前就是无法使用，无代理也无法获取IP地址，网络正常

![image](https://github.com/user-attachments/assets/17216316-4ca8-4962-8d0c-fddd040af09a)

**Comment by Just-Hack-For-Fun** [comment]
师傅，你可以在程序主页面同时按 Ctrl + Shift + i 开启开发者工具，可以看一下控制台有哪些报错

**Comment by yinsel** [comment]
> 师傅，你可以在程序主页面同时按 Ctrl + Shift + i 开启开发者工具，可以看一下控制台有哪些报错

窗口不可调整，看不到可能得重新编译

**Comment by Just-Hack-For-Fun** [comment]
我在 Windows 11 上测试过，会在额外窗口打开开发者工具，当然你可以考虑直接使用源代码进行测试，看看问题到底出在哪里

**Comment by yinsel** [comment]
> 我在 Windows 11 上测试过，会在额外窗口打开开发者工具，当然你可以考虑直接使用源代码进行测试，看看问题到底出在哪里

问题是https://api.ipify.org/?format=json访问不了。。。

**Comment by Just-Hack-For-Fun** [comment]
确实啊，这个网址好像被墙了，不是师傅你这边的原因，不过记录IP功能是通过 ipipnet 来进行的，应该不受影响，感谢反馈

**Comment by yinsel** [comment]
> 确实啊，这个网址好像被墙了，不是师傅你这边的原因，不过记录IP功能是通过 ipipnet 来进行的，应该不受影响，感谢反馈

还有一个问题 就是安装完后建议自动添加快捷方式0.0

**Comment by Just-Hack-For-Fun** [comment]
这个我得过一段时间研究一下 Electron-Forge 的配置，应该是可以做到的，不难，这段时间可能出行，回来研究，感谢师傅反馈

**Comment by Just-Hack-For-Fun** [comment]
师傅们，新版本已经更新，已解决一直获取IP地址的问题，增加了自动创建快捷方式的功能
